### ISSUE TITLE
nbactions.xml is not filled in

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#19]
The nbactions.xml file created by the archetypes (at least the skeleton archetype) appears to be a template, not a completed file:

I suggest just removing this from the archive completely.

**Comment by elharo** [comment]
Hmm, doesn't seem to happen with the guestbook

**Comment by lesv** [comment]
#26 appears to fix this.

I'm ok w/ removing, but @ludoch likes it.
