### ISSUE TITLE
Upgrade default app engine sdk to 1.9.38

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#20]
[INFO] [INFO] Downloading: https://repo.maven.apache.org/maven2/com/google/appengine/appengine-maven-plugin/1.9.25/appengine-maven-plugin-1.9.25.pom
[INFO] [INFO] Downloaded: https://repo.maven.apache.org/maven2/com/google/appengine/appengine-maven-plugin/1.9.25/appengine-maven-plugin-1.9.25.pom (15 KB at 119.6 KB/sec)

**Comment by lesv** [comment]
#28 does this for all 4 archetypes
