### ISSUE TITLE
specify UTF-8 as encoding in pom.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#21]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ appengine-skeleton-archetype ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 9 resources
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ appengine-skeleton-archetype ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

**Comment by lesv** [comment]
Bizarrely, the correct setting was already in the file. https://maven.apache.org/general.html#encoding-warning

I've added another in #28

**Comment by lesv** [comment]
Fixed
