### ISSUE TITLE
Use new maven plugin

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#24]
At some point (when?) we need to update the archetypes to use the new maven plugin @loosebazooka is working on. For Cloud Tools for Eclipse this is preferably sooner rather than later. However the new plugin is not yet ready for general use.

Should we create a new archetype? a new version of the skeleton archetype?

@arouzrokh @lesv  @ludoch

**Comment by lesv** [comment]
What we will do next Q is upgrade all the samples to use maven, Gradle, Intellij, and Eclipse.
We might also add Netbeans at the same time.

At the moment, maven support in Eclipse is not a bad way to do things.

We'll want to upgrade everything at once ideally.

**Comment by rdayal** [comment]
I guess the thing is for the Cloud Tools for Eclipse, it is blocking us to not have an archetype that uses the app-maven-plugin. 

Can we create another archetype temporarily just to get us unblocked? We can mark it as alpha or some such.

**Comment by ludoch** [comment]
+1 on a new temp archetype.
We just cannot force existing customers to use something which is not ready
and under development.
I guess we would need a 'switch' criteria that maps the capabilities of the
existing stack with the replacement and decide when to switch (including
samples/docs).

**Comment by lesv** [comment]
There doesn't appear to be such a thing as a temporary archetype once we publish it, it's there forever, we can update it to say it's deprecated, but we can't get rid of it.

That said, if you are happy with that. I'm ok with that.

**Comment by elharo** [comment]
I'm fine with a new archetype. Les is right that we can't unpublish a released archetype.

**Comment by rdayal** [comment]
Les - let's go with a new archetype that we basically mark as "do not use/deprecated" for now. 

Is that okay with you? If so, should I just go ahead and create it, and send you a pull request for it (and you could push it up to maven central)?

**Comment by rdayal** [comment]
Actually, we could also just create the archetype and publish it to a temporary GCS bucket for now. Once we are ready to really promote it and make it official, we can push it to Maven Central. We can still develop it in this repo though.

https://numberformat.wordpress.com/2009/11/15/creating-a-new-maven-archetype-and-publishing-it-to-nexus/

Thoughts?

**Comment by loosebazooka** [comment]
Can we publish snapshots? Or is that not relevant here?

**Comment by lesv** [comment]
Snapshots aren't relevant here.

We can publish to a bucket, but it would require you add to your sites.xml file to use.

**Comment by rdayal** [comment]
Ok. Sounds like we have a way forward. 

@elharo Can you create a new archetype in this repo that uses that app-maven-plugin? We'll publish it to a GCS bucket.

**Comment by elharo** [comment]
On Mon, Jun 13, 2016 at 1:25 PM, rdayal notifications@github.com wrote:

> Ok. Sounds like we have a way forward.
> 
> @elharo https://github.com/elharo Can you create a new archetype in
> this repo that uses that app-maven-plugin? We'll publish it to a GCS bucket.

Sure. What should we call it? Maybe gcp-skeleton-archetype?

## 

Elliotte Rusty Harold
elharo@macfaq.com

**Comment by rdayal** [comment]
That sounds good to me.
