### ISSUE TITLE
Add unit test to appengine-skeleton-archetype

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/appengine-maven-archetypes-java#32]
A simple unit test that uses a mock HttpServletResponse (also contained in the archetype). Add JUnit and Hamcrest-core dependencies.
Required for https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/issues/706

**Comment by lesv** [comment]
I need to redo the archetypes, but it won't be for at least a week.

**Comment by lesv** [comment]
Assign to me for now.

**Comment by lesv** [comment]
I've superseded this by appengine-standard-archetype & appengine-flexible-archetype.  I'm going to leave this to remind me to deprecate this archetype once we can fix docs again.

**Comment by lesv** [comment]
Added to #63
