### ISSUE TITLE
maven-war-plugin should be version 2.6 in standard archetype

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#35]
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.0.0</version>

Version 3.0 is incompatible with m2e in Eclipse Mars 4.5.2 as discussed here:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/792
http://stackoverflow.com/questions/37555557/m2e-error-in-mavenarchiver-getmanifest

**Comment by lesv** [comment]
released
