### ISSUE TITLE
maven-war-plugin should be version 2.6 in flex archetype

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#37]
Version 3.0 is incompatible with m2e in Eclipse Mars 4.5.2 as discussed here:

GoogleCloudPlatform/google-cloud-eclipse#792
http://stackoverflow.com/questions/37555557/m2e-error-in-mavenarchiver-getmanifest

**Comment by lesv** [comment]
I still have to do stuff here.

**Comment by lesv** [comment]
released
