### ISSUE TITLE
Remove <application> in appengine-web.xml

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-maven-archetypes-java#42]
The comment sounds troubling.

``` xml
<application>not-needed</application> <!-- no longer be required (in a week or so) -->
```

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-standard-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/appengine-web.xml#L6

**Comment by elharo** [comment]
It's not needed today if you're using gcloud 131.0
