### ISSUE TITLE
pom.xml is not filtered="true"

### ISSUE THREAD

**Issue by okulev** [GoogleCloudPlatform/appengine-maven-archetypes-java#47]
Using `appengine-skeleton-archetype`, NetBeans generates `pom.xml` that starts with the following lines before `<?xml version="1.0" encoding="UTF-8"?>`:

```
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
```

In NetBeans, this leads to IDE errors that doesn't seem to affect functionality but anyway it needs fixing: http://statistics.netbeans.org/analytics/detail.do?id=218308

Searching for the cause, I found that probably `filtered="true"` is missing: http://stackoverflow.com/questions/3085893/edit-source-files-with-custom-maven-archetype but it looks like `pom.xml` is not listed in https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-skeleton-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml

Please fix the archetype.

**Comment by lesv** [comment]
#63 fixes
