### ISSUE TITLE
nbactions.xml in guestbook-example needs to be fixed or removed

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-maven-archetypes-java#48]
The goals in `nbactions.xml` are the old plugin goals:

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/guestbook-archetype/src/main/resources/archetype-resources/nbactions.xml#L7

**Comment by lesv** [comment]
Ah - Agree - they need to be dynamic as well.

**Comment by lesv** [comment]
@elharo / @chanseokoh Do you use the eclipse-launch-profiles?  And do you care that they are correct?

**Comment by elharo** [comment]
Haven't checked, but I doubt these are necessary *if* Cloud Tools for Eclipse is installed. They might be useful if it isn't.

**Comment by elharo** [comment]
Just checked. Definitely not needed if CT4E is installed.

**Comment by elharo** [comment]
And if CT4E isn't installed they still don't seem to do anything. Delete them.

**Comment by lesv** [comment]
#63 fixes
