### ISSUE TITLE
Where did HelloInfo come from?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#52]
and why is its test code in HelloAppEngineTest?

**Comment by chanseokoh** [comment]
I was confused about the existence of `HelloInfo` at first. It's being used from `index.jsp`.

**Comment by lesv** [comment]
Just trying to show how to do some things, it will get annoying when creating projects, so I'm Ok killing it.

**Comment by lesv** [comment]
#63 fixes.
