### ISSUE TITLE
Upgrade to Guava 20

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#55]
<guava.version>18.0</guava.version>

-->

    <guava.version>20.0</guava.version>

21 won't work because it requires Java 8. This should hold us until 22 comes out with a Java 7 compatible version.

**Comment by ludoch** [comment]
Can we do e2e tests with Cloud Endpoints v2 and Java Veener libraries? I think both of them carry a guava dependency, and I remember Endpoints having issues with a previous Guava version... I think Veener also add GuavaJDK5 only version, so you end up with multiple guava in the path, if you are not careful with excludes...

**Comment by elharo** [comment]
And while we're at it we should move Objectify to 5.1.15

<objectify.version>5.1.13</objectify.version>
<guava.version>18.0</guava.version>

**Comment by lesv** [comment]
#63 fixes
