### ISSUE TITLE
local variable not used in HelloInfoTest

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#56]
@Test
  public void HelloInfo_test() {
    String result = HelloInfo.getInfo();
    assertThat(HelloInfo.getInfo())
      .named("HelloInfo.getInfo")
      .containsMatch("^Version:\\s+.+OS:\\s+.+User:\\s");
  }

**Comment by lesv** [comment]
Please mention which archetype -- though I'll find it.

**Comment by lesv** [comment]
#63 fixes
