### ISSUE TITLE
Stop requiring gcloud-version

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#59]
It appears we require gcloud-version property in the skeleton archetype (and nowhere else) but do not actually reference it:

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/search?utf8=%E2%9C%93&q=gcloud-version

If so, we should remove this.

**Comment by branflake2267** [comment]
It's referenced in the pom.xml properties. There are two not getting replaced. 
1. ${appengine.sdk.version}
2. ${gcloud.plugin.version}

Generated Pom.xml. 
```
<properties>
        <app.id>your-app-id</app.id>
        <app.version>1</app.version>
        <appengine.version>${appengine.sdk.version}</appengine.version>
        <gcloud.plugin.version>${gcloud.plugin.version}</gcloud.plugin.version>
```

```
//...
            <plugin>
              <groupId>com.google.appengine</groupId>
              <artifactId>gcloud-maven-plugin</artifactId>
              <version>${gcloud.plugin.version}</version>
              <configuration>
                <set_default>true</set_default>
              </configuration>
            </plugin>
```

<img width="705" alt="screen shot 2017-03-10 at 5 28 11 pm" src="https://cloud.githubusercontent.com/assets/1326504/23819172/8baf115e-05b7-11e7-84be-942874246dd4.png">

**Comment by lesv** [comment]
Totally agree

**Comment by lesv** [comment]
#63 fixes
