### ISSUE TITLE
Parameterize appengine-api

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-maven-archetypes-java#60]
I.e. don't add it unless requested as we do for objectify.

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-standard-archetype/src/main/resources/archetype-resources/pom.xml

**Comment by chanseokoh** [comment]
Precisely speaking, it is parameterized, but it is fixed at the same time. Therefore, it may end up having duplicate dependency entries.

**Comment by lesv** [comment]
Why?  If we are doing an appEngine project, why not include the API as a convenience for the user?

**Comment by lesv** [comment]
I'm inclined to close this.
